name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: List directory contents
        run: ls -la
      - name: Ruff-action
        uses: astral-sh/ruff-action@v2
        with:
         args: "check . --ignore FIX002,F841,TD003" # todo comments, unused rot_mc
         src: "/home/runner/work/aruco-slam"
